messages:
  - Ce faci Lopatica?
  - Muie steaua.
  - Mergem la mare.
  - Adina e o vacuta.
  - Mamaia ta e tigan.
  - I Like Trains.
  - Mi-am prins p**a'n aspirator.
  - S'ombag... ce urata e.
  - Vreau la sinaia.